[opener]
markdown = [
  # { run = 'nvim "$@"', block = true, for = "unix" },
  # { run = '/Users/brightowl/.local/bin/nvim "$@"', block = true, for = "unix" },
  { run = "open -a MacDown.app \"$1\"", desc = "Open with MacDown" },
]
video = [
  { run = "open \"$1\"", desc = "Open with default player" },
  { run = "open -a IINA.app \"$1\"", desc = "Open with IINA" },
  { run = "open -a VLC.app \"$1\"", desc = "Open with VLC" },
  { run = "open -a \"QuickTime Player\" \"$1\"", desc = "Open with QuickTime Player" },
]


[open]
prepend_rules = [
  { mime = "video/*", use = "video" },
  { name="*.md", use = "markdown" },
  { mime = "text/markdown", use = "markdown" },
]

[manager]
ratio = [1, 3, 4]
show_symlink=true
# show_hidden=true

[preview]
wrap = "yes"

[key]
# Toggle hidden files
"." = "toggle_hidden"


