# Generated by Nix home-manager activation
# This file is writable but will be regenerated on next home-manager switch

export PNPM_HOME=/Users/brightowl/Library/pnpm
export NIX_CURRENT_SYSTEM_BIN=/run/current-system/sw/bin
export NIX_CURRENT_USER_BIN=/Users/brightowl/.nix-profile/bin
export HM_PROFILE="/Users/brightowl/.local/state/nix/profiles/home-manager"
export HOMEBREW_BIN="/opt/homebrew/bin"

export PATH="$HM_PROFILE/bin:$NIX_CURRENT_SYSTEM_BIN:$NIX_CURRENT_USER_BIN:/Users/brightowl/.local/bin:/Users/brightowl/.config/emacs/bin:/Users/brightowl/bin:/usr/local/bin:$PNPM_HOME:$HOMEBREW_BIN:$PATH"
