
# export BAT_THEME=$(rg -q 'light' ~/.colorscheme 2>/dev/null && echo "light" || echo "dark")
# note ~/.dotfiles/bin/bat now wraps bat to assign theme based on ~/.colorscheme, so this survives
# edge cases such as running toggle_theme within hammerspoon keybind

export ZSH_CONFIG="$HOME/.dotfiles/zsh"

source $ZSH_CONFIG/constants.zsh
source $ZSH_CONFIG/shell_functions.sh
source $ZSH_CONFIG/aliases.zsh
source $ZSH_CONFIG/bindkeys.zsh
source $ZSH_CONFIG/preferences.zsh
source $ZSH_CONFIG/terminal_styling.zsh
source $ZSH_CONFIG/completions.zsh
# source $ZSH_CONFIG/fast_compinit.zsh
# source $ZSH_CONFIG/after_compinit.zsh

_plugins_zsh=$HOME/.zsh_plugins.zsh
_plugins_txt=$HOME/.zsh_plugins.txt

if [[ -f $_plugins_txt && ( ! -f $_plugins_zsh || $_plugins_txt -nt $_plugins_zsh ) ]]; then
    echo 'sourcing plugins txt file'
    source "$PKGS_ANTIDOTE/share/antidote/antidote.zsh" #variable set in zshenv during nix build step
    antidote load
elif [[ -f $_plugins_zsh ]]; then
    source $_plugins_zsh
fi 

#NOTE: WIP: idea is to persist 'fzd file' cache not per shell session (i.e. each pid)
#but rather across all interactive shell session .. currently using marker files in /tmp/fzd_sessions/
#Need to change fzd defintion to use marker files existence

 fzd_shells_init
 on_exit() {
   fzd_shells_cleanup
   # echo 'trap exit ran'
   # echo "cleanup fired for $$" >> /tmp/cleanup.log
 }

 trap on_exit EXIT HUP 
 #subtle bug all along: HUP is needed on mac when terminal window closes (SIGHUP sent)
 #explains why without it and running 'time zsh -ic exit' things would work still, 
 #but not when closing and re-opening terminal window!
 

 

